# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=256)),
                ('question_text', models.CharField(max_length=256)),
                ('answer_1', models.CharField(max_length=128)),
                ('answer_2', models.CharField(max_length=128)),
                ('answer_3', models.CharField(max_length=128)),
                ('answer_4', models.CharField(max_length=128)),
            ],
        ),
    ]
