# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=256)),
                ('question_text', models.CharField(max_length=256)),
                ('true_answer', models.IntegerField(default=1)),
            ],
        ),
    ]
