# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonQuiz', '0004_auto_20161022_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='map',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='map',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='map',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.CharField(default='default', max_length=256),
        ),
    ]
