# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonQuiz', '0005_auto_20161022_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HorizonQuiz.Map'),
        ),
    ]
