# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonQuiz', '0006_region_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_capital_area',
            field=models.BooleanField(default=False),
        ),
    ]
