# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HorizonQuiz', '0007_region_is_capital_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='none', max_length=256)),
                ('name', models.CharField(default='', max_length=128)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='region',
            name='height',
        ),
        migrations.RemoveField(
            model_name='region',
            name='url',
        ),
        migrations.RemoveField(
            model_name='region',
            name='width',
        ),
        migrations.AddField(
            model_name='region',
            name='reg_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HorizonQuiz.RegionType'),
        ),
    ]
